// Mock data for development and testing
// Replace with actual API calls in production

export const MOCK_BOOKINGS = [
  {
    id: 1,
    studentId: 1,
    studentName: "Karthikeyan S",
    equipmentId: 1,
    equipmentName: "Digital Oscilloscope",
    labId: 1,
    labName: "Electronics Lab",
    bookingDate: "2026-07-01",
    startTime: "09:00",
    endTime: "11:00",
    duration: 2,
    status: "confirmed",
    approvedBy: "Dr. Priya R",
    reason: "ECE Lab practical session",
    createdAt: "2026-06-30T10:00:00Z",
  },
  {
    id: 2,
    studentId: 2,
    studentName: "Hariharan A",
    equipmentId: 2,
    equipmentName: "Arduino Uno Kit",
    labId: 2,
    labName: "Embedded Systems Lab",
    bookingDate: "2026-07-01",
    startTime: "10:30",
    endTime: "12:30",
    duration: 2,
    status: "pending",
    reason: "Microcontroller programming",
    createdAt: "2026-06-30T11:15:00Z",
  },
  {
    id: 3,
    studentId: 3,
    studentName: "Premnath P",
    equipmentId: 3,
    equipmentName: "3D Printer",
    labId: 3,
    labName: "Manufacturing Lab",
    bookingDate: "2026-07-02",
    startTime: "14:00",
    endTime: "16:00",
    duration: 2,
    status: "pending",
    reason: "Prototype printing",
    createdAt: "2026-06-30T12:45:00Z",
  },
  {
    id: 4,
    studentId: 4,
    studentName: "Nivetha R",
    equipmentId: 4,
    equipmentName: "Network Analyzer",
    labId: 4,
    labName: "Communication Lab",
    bookingDate: "2026-07-02",
    startTime: "11:00",
    endTime: "13:00",
    duration: 2,
    status: "confirmed",
    approvedBy: "Dr. Mahesh K",
    reason: "RF measurement training",
    createdAt: "2026-06-29T14:30:00Z",
  },
  {
    id: 5,
    studentId: 1,
    studentName: "Karthikeyan S",
    equipmentId: 5,
    equipmentName: "PLC Trainer Kit",
    labId: 5,
    labName: "Automation Lab",
    bookingDate: "2026-07-03",
    startTime: "09:00",
    endTime: "11:00",
    duration: 2,
    status: "completed",
    approvedBy: "Dr. Priya R",
    reason: "PLC programming",
    createdAt: "2026-06-28T10:00:00Z",
  },
];

export const MOCK_EQUIPMENT = [
  {
    id: 1,
    name: "Digital Oscilloscope",
    assetId: "EQ-101",
    labId: 1,
    labName: "Electronics Lab",
    category: "Electronic Testing Equipment",
    status: "available",
    condition: "good",
    lastMaintenance: "2026-06-15",
    nextMaintenance: "2026-07-15",
    utilizationRate: "82%",
    totalBookings: 45,
    description: "2 Channel Digital Oscilloscope 100MHz",
  },
  {
    id: 2,
    name: "Arduino Uno Kit",
    assetId: "EQ-102",
    labId: 2,
    labName: "Embedded Systems Lab",
    category: "Microcontroller Kit",
    status: "in-use",
    condition: "good",
    lastMaintenance: "2026-06-20",
    nextMaintenance: "2026-07-20",
    utilizationRate: "76%",
    totalBookings: 38,
    description: "Arduino Uno R3 Development Board with sensors",
  },
  {
    id: 3,
    name: "3D Printer",
    assetId: "EQ-117",
    labId: 3,
    labName: "Manufacturing Lab",
    category: "Printing Equipment",
    status: "maintenance",
    condition: "fair",
    lastMaintenance: "2026-06-10",
    nextMaintenance: "2026-07-10",
    utilizationRate: "69%",
    totalBookings: 32,
    description: "FDM 3D Printer with heated bed",
  },
  {
    id: 4,
    name: "Network Analyzer",
    assetId: "EQ-130",
    labId: 4,
    labName: "Communication Lab",
    category: "RF Testing Equipment",
    status: "available",
    condition: "excellent",
    lastMaintenance: "2026-06-25",
    nextMaintenance: "2026-08-25",
    utilizationRate: "58%",
    totalBookings: 28,
    description: "RF Network Analyzer 1MHz-6GHz",
  },
  {
    id: 5,
    name: "PLC Trainer Kit",
    assetId: "EQ-145",
    labId: 5,
    labName: "Automation Lab",
    category: "Industrial Control",
    status: "available",
    condition: "good",
    lastMaintenance: "2026-06-18",
    nextMaintenance: "2026-07-18",
    utilizationRate: "63%",
    totalBookings: 31,
    description: "Siemens S7-1200 PLC Training System",
  },
];

export const MOCK_FAULTS = [
  {
    id: 1,
    faultId: "FT-501",
    equipmentId: 3,
    equipmentName: "3D Printer",
    labId: 3,
    labName: "Manufacturing Lab",
    reportedBy: "Premnath P",
    reportedByStudentId: 3,
    reportedDate: "2026-06-29T14:30:00Z",
    status: "open",
    severity: "high",
    description: "Nozzle temperature not reaching desired value",
    observations: "Printer is heating slowly and not reaching 210°C",
    resolution: null,
    resolvedAt: null,
  },
  {
    id: 2,
    faultId: "FT-502",
    equipmentId: 2,
    equipmentName: "Arduino Uno Kit",
    labId: 2,
    labName: "Embedded Systems Lab",
    reportedBy: "Karthikeyan S",
    reportedByStudentId: 1,
    reportedDate: "2026-06-29T10:15:00Z",
    status: "in-progress",
    severity: "low",
    description: "USB connection intermittent",
    observations: "Sometimes loses connection when uploading code",
    resolution: null,
    resolvedAt: null,
  },
  {
    id: 3,
    faultId: "FT-503",
    equipmentId: 1,
    equipmentName: "Digital Oscilloscope",
    labId: 1,
    labName: "Electronics Lab",
    reportedBy: "Hariharan A",
    reportedByStudentId: 2,
    reportedDate: "2026-06-28T15:45:00Z",
    status: "resolved",
    severity: "medium",
    description: "Probe calibration drift",
    observations: "Measurements off by 2% on CH1",
    resolution: "Performed full calibration",
    resolvedAt: "2026-06-29T11:20:00Z",
  },
  {
    id: 4,
    faultId: "FT-504",
    equipmentId: 6,
    equipmentName: "Hydraulic Test Rig",
    labId: 6,
    labName: "Mechanical Lab",
    reportedBy: "Nivetha R",
    reportedByStudentId: 4,
    reportedDate: "2026-06-28T09:00:00Z",
    status: "open",
    severity: "critical",
    description: "Pressure gauge shows inconsistent readings",
    observations: "Gauge fluctuates between safe and unsafe readings",
    resolution: null,
    resolvedAt: null,
  },
];

export const MOCK_USERS = [
  {
    id: 1,
    userId: "717824226",
    name: "Karthikeyan S",
    email: "karthikeyan@college.edu",
    role: "STUDENT",
    department: "IT",
    status: "active",
    joinDate: "2024-01-15",
    createdAt: "2024-01-15T08:00:00Z",
  },
  {
    id: 2,
    userId: "717824227",
    name: "Hariharan A",
    email: "hariharan@college.edu",
    role: "STUDENT",
    department: "CSE",
    status: "active",
    joinDate: "2024-01-16",
    createdAt: "2024-01-16T08:00:00Z",
  },
  {
    id: 3,
    userId: "717824228",
    name: "Premnath P",
    email: "premnath@college.edu",
    role: "STUDENT",
    department: "Mechanical",
    status: "active",
    joinDate: "2024-01-17",
    createdAt: "2024-01-17T08:00:00Z",
  },
  {
    id: 4,
    userId: "717824229",
    name: "Nivetha R",
    email: "nivetha@college.edu",
    role: "STUDENT",
    department: "ECE",
    status: "active",
    joinDate: "2024-01-18",
    createdAt: "2024-01-18T08:00:00Z",
  },
  {
    id: 5,
    userId: "FAC001",
    name: "Dr. Priya R",
    email: "priya@college.edu",
    role: "FACULTY",
    department: "ECE",
    status: "active",
    joinDate: "2023-08-01",
    createdAt: "2023-08-01T08:00:00Z",
  },
  {
    id: 6,
    userId: "FAC002",
    name: "Dr. Mahesh K",
    email: "mahesh@college.edu",
    role: "FACULTY",
    department: "Mechanical",
    status: "active",
    joinDate: "2023-08-05",
    createdAt: "2023-08-05T08:00:00Z",
  },
  {
    id: 7,
    userId: "FAC003",
    name: "Dr. Amit S",
    email: "amit@college.edu",
    role: "FACULTY",
    department: "IT",
    status: "active",
    joinDate: "2023-08-10",
    createdAt: "2023-08-10T08:00:00Z",
  },
  {
    id: 8,
    userId: "ADM001",
    name: "Admin User",
    email: "admin@college.edu",
    role: "ADMIN",
    department: "Administration",
    status: "active",
    joinDate: "2023-07-01",
    createdAt: "2023-07-01T08:00:00Z",
  },
];
